import os
import shutil

languages = {
    'en': {
        'lang="de"': 'lang="en"',
        'Partnerschaften & Anfragen': 'Partnerships & Inquiries',
        'Reichen Sie Ihre Geschäftsidee ein, registrieren Sie sich als Investor oder stellen Sie Miet- und Kaufanfragen für unsere Projekte.': 'Submit your business idea, register as an investor, or submit rental and purchase requests for our projects.',
        'Home': 'Home',
        '/de/': '/en/',
        '>Deutschland<': '>Germany<',
        '>Türkei<': '>Turkey<',
        '>Anfragen<': '>Inquiries<',
        '>Kontakt<': '>Contact<',
        'Wählen Sie Ihren Bereich, um schnell und unkompliziert mit uns in Kontakt zu treten.': 'Select your area to easily and quickly get in touch with us.',
        'Idee einreichen': 'Submit Idea',
        'Für Projektideen & strategische Partnerschaften (Investor gesucht)': 'For project ideas & strategic partnerships (Investor wanted)',
        'Als Investor registrieren': 'Register as Investor',
        'Für Investoren an unseren Projekten oder Grundstücken': 'For investors in our projects or properties',
        'Mieten': 'Rent',
        'Immobilien oder Gewerbeflächen für Ihre Firma mieten': 'Rent properties or commercial spaces for your company',
        'Kaufen': 'Buy',
        'Immobilien, Grundstücke oder Beteiligungen erwerben': 'Buy properties, land, or acquire project stakes',
        'Zurück zur Auswahl': 'Back to selection',
        'Vielen Dank für Ihre Anfrage!': 'Thank you for your inquiry!',
        'Wir haben Ihre Daten erhalten und werden uns in Kürze bei Ihnen melden.': 'We have received your data and will contact you shortly.',
        'Weitere Anfrage stellen': 'Submit another inquiry',
        'Idee einreichen (Investor gesucht)': 'Submit Idea (Investor wanted)',
        'Wenn Sie eine interessante Geschäftsidee haben und einen Investor oder strategischen Partner suchen, können Sie Ihre Idee bei uns einreichen. Wir prüfen jede Anfrage individuell. Wenn das Projekt zu uns passt, können wir selbst als Investor oder Partner einsteigen.': 'If you have an interesting business idea and are seeking an investor or strategic partner, you can submit your idea to us. We review each inquiry individually. If the project is a good fit, we may step in as an investor or partner.',
        '>Name *<': '>Name *<',
        'Firma (optional)': 'Company (optional)',
        '>E-Mail *<': '>Email *<',
        'Telefon (optional)': 'Phone (optional)',
        '>Land *<': '>Country *<',
        '>Stadt *<': '>City *<',
        '>Kategorie der Idee *<': '>Idea Category *<',
        '>Bitte wählen<': '>Please select<',
        '>Immobilienentwicklung<': '>Real Estate Development<',
        '>Technologie / Start-up<': '>Technology / Startup<',
        '>Erneuerbare Energien<': '>Renewable Energy<',
        '>Handel & Gewerbe<': '>Commerce & Trade<',
        '>Sonstiges<': '>Other<',
        'Was wird gesucht? *': 'What are you looking for? *',
        'Investor (Kapital)': 'Investor (Capital)',
        'Strategischer Partner': 'Strategic Partner',
        'Fläche / Grundstück': 'Space / Land',
        'Zusammenarbeit / Joint-Venture': 'Collaboration / Joint Venture',
        'Benötigte Investitionssumme (optional)': 'Required Investment Amount (optional)',
        'Beschreibung der Idee *': 'Description of the Idea *',
        'Datei Upload (PDF oder Präsentation) - optional': 'File Upload (PDF or Presentation) - optional',
        'Anfrage senden': 'Send Inquiry',
        'Investoren können sich registrieren, um passende Projekte, Grundstücke oder Geschäftsmöglichkeiten mit uns zu besprechen.': 'Investors can register to discuss suitable projects, land, or business opportunities with us.',
        'Bevorzugte Branche': 'Preferred Industry',
        'Bevorzugte Region': 'Preferred Region',
        'Investitionsvolumen': 'Investment Volume',
        'Beschreibung / Nachricht *': 'Description / Message *',
        'Was möchten Sie mieten? *': 'What would you like to rent? *',
        '>Grundstück<': '>Land<',
        '>Gewerbeobjekt<': '>Commercial Property<',
        '>Ladenfläche<': '>Retail Space<',
        '>Wohnung<': '>Apartment<',
        '>Büro<': '>Office<',
        'Gewünschte Größe': 'Desired Size',
        '>Budget<': '>Budget<',
        '>Nutzungszweck<': '>Intended Use<',
        '>Nachricht *<': '>Message *<',
        'Mietanfrage senden': 'Send Rental Inquiry',
        'Was möchten Sie kaufen? *': 'What would you like to buy? *',
        '>Immobilie<': '>Property<',
        'Beteiligung an Projekt': 'Project Stake',
        '>Anforderungen<': '>Requirements<',
        'Kaufanfrage senden': 'Send Purchase Inquiry',
        'Nutzungsbedingungen': 'Terms of Use',
        'Cookie-Richtlinie': 'Cookie Policy',
        'Datenschutz': 'Privacy Policy',
        'ihre@email.com': 'your@email.com',
        'Ihr Name': 'Your Name',
        'Ihr vollständiger Name': 'Your Full Name',
        'Firmenname': 'Company Name',
        'Land der Umsetzung': 'Country of Implementation',
        'Wo suchen Sie?': 'Where are you looking?',
        'z.B. DACH, USA, Global': 'e.g., DACH, USA, Global',
        'Geplantes Volumen': 'Planned Volume',
        'Kurze Beschreibung Ihres Investmentfokus...': 'Brief description of your investment focus...',
        'Weitere Details zu Ihrer Anfrage...': 'More details about your inquiry...',
        'Beschreiben Sie kurz Ihr Vorhaben...': 'Briefly describe your project...'
    },
    'es': {
        'lang="de"': 'lang="es"',
        'Partnerschaften & Anfragen': 'Asociaciones y Consultas',
        'Reichen Sie Ihre Geschäftsidee ein, registrieren Sie sich als Investor oder stellen Sie Miet- und Kaufanfragen für unsere Projekte.': 'Envíe su idea de negocio, regístrese como inversor o envíe solicitudes de alquiler y compra para nuestros proyectos.',
        'Home': 'Inicio',
        '/de/': '/es/',
        '>Deutschland<': '>Alemania<',
        '>Türkei<': '>Turquía<',
        '>Anfragen<': '>Consultas<',
        '>Kontakt<': '>Contacto<',
        'Wählen Sie Ihren Bereich, um schnell und unkompliziert mit uns in Kontakt zu treten.': 'Seleccione su área para ponerse en contacto con nosotros de forma rápida y sencilla.',
        'Idee einreichen': 'Enviar idea',
        'Für Projektideen & strategische Partnerschaften (Investor gesucht)': 'Para ideas de proyectos y asociaciones estratégicas (Se busca inversor)',
        'Als Investor registrieren': 'Registrarse como inversor',
        'Für Investoren an unseren Projekten oder Grundstücken': 'Para inversores en nuestros proyectos o terrenos',
        'Mieten': 'Alquilar',
        'Immobilien oder Gewerbeflächen für Ihre Firma mieten': 'Alquile inmuebles o espacios comerciales para su empresa',
        'Kaufen': 'Comprar',
        'Immobilien, Grundstücke oder Beteiligungen erwerben': 'Adquirir inmuebles, terrenos o inversiones',
        'Zurück zur Auswahl': 'Volver a la selección',
        'Vielen Dank für Ihre Anfrage!': '¡Gracias por su consulta!',
        'Wir haben Ihre Daten erhalten und werden uns in Kürze bei Ihnen melden.': 'Hemos recibido sus datos y nos pondremos en contacto en breve.',
        'Weitere Anfrage stellen': 'Enviar otra consulta',
        'Idee einreichen (Investor gesucht)': 'Enviar idea (Se busca inversor)',
        'Wenn Sie eine interessante Geschäftsidee haben und einen Investor oder strategischen Partner suchen, können Sie Ihre Idee bei uns einreichen. Wir prüfen jede Anfrage individuell. Wenn das Projekt zu uns passt, können wir selbst als Investor oder Partner einsteigen.': 'Si tiene una idea de negocio y busca un inversor o socio, envíela aquí. Revisamos cada consulta individualmente.',
        '>Name *<': '>Nombre *<',
        'Firma (optional)': 'Empresa (opcional)',
        '>E-Mail *<': '>Correo electrónico *<',
        'Telefon (optional)': 'Teléfono (opcional)',
        '>Land *<': '>País *<',
        '>Stadt *<': '>Ciudad *<',
        '>Kategorie der Idee *<': '>Categoría de la idea *<',
        '>Bitte wählen<': '>Seleccionar<',
        '>Immobilienentwicklung<': '>Desarrollo Inmobiliario<',
        '>Technologie / Start-up<': '>Tecnología / Startup<',
        '>Erneuerbare Energien<': '>Energías Renovables<',
        '>Handel & Gewerbe<': '>Comercio<',
        '>Sonstiges<': '>Otros<',
        'Was wird gesucht? *': '¿Qué está buscando? *',
        'Investor (Kapital)': 'Inversor (Capital)',
        'Strategischer Partner': 'Socio estratégico',
        'Fläche / Grundstück': 'Espacio / Terreno',
        'Zusammenarbeit / Joint-Venture': 'Colaboración / Joint Venture',
        'Benötigte Investitionssumme (optional)': 'Suma de inversión (opcional)',
        'Beschreibung der Idee *': 'Descripción de la idea *',
        'Datei Upload (PDF oder Präsentation) - optional': 'Subir archivo (PDF o Presentación)',
        'Anfrage senden': 'Enviar consulta',
        'Investoren können sich registrieren, um passende Projekte, Grundstücke oder Geschäftsmöglichkeiten mit uns zu besprechen.': 'Los inversores pueden registrarse para discutir proyecciones y oportunidades.',
        'Bevorzugte Branche': 'Sector preferido',
        'Bevorzugte Region': 'Región preferida',
        'Investitionsvolumen': 'Volumen de inversión',
        'Beschreibung / Nachricht *': 'Descripción / Mensaje *',
        'Was möchten Sie mieten? *': '¿Qué desea alquilar? *',
        '>Grundstück<': '>Terreno<',
        '>Gewerbeobjekt<': '>Local comercial<',
        '>Ladenfläche<': '>Espacio comercial<',
        '>Wohnung<': '>Piso<',
        '>Büro<': '>Oficina<',
        'Gewünschte Größe': 'Tamaño deseado',
        '>Budget<': '>Presupuesto<',
        '>Nutzungszweck<': '>Uso previsto<',
        '>Nachricht *<': '>Mensaje *<',
        'Mietanfrage senden': 'Enviar solicitud de alquiler',
        'Was möchten Sie kaufen? *': '¿Qué desea comprar? *',
        '>Immobilie<': '>Propiedad<',
        'Beteiligung an Projekt': 'Participación en proyecto',
        '>Anforderungen<': '>Requisitos<',
        'Kaufanfrage senden': 'Enviar solicitud de compra',
        'Nutzungsbedingungen': 'Términos de Uso',
        'Cookie-Richtlinie': 'Política de Cookies',
        'Datenschutz': 'Política de Privacidad',
        'ihre@email.com': 'su@email.com',
        'Ihr Name': 'Su Nombre',
        'Ihr vollständiger Name': 'Su Nombre Completo',
        'Firmenname': 'Empresa',
        'Land der Umsetzung': 'País de ejecución',
        'Wo suchen Sie?': '¿Dónde busca?',
        'z.B. DACH, USA, Global': 'ej. EE.UU., Global',
        'Geplantes Volumen': 'Volumen planificado',
        'Kurze Beschreibung Ihres Investmentfokus...': 'Breve descripción de su enfoque de inversión...',
        'Weitere Details zu Ihrer Anfrage...': 'Más detalles...',
        'Beschreiben Sie kurz Ihr Vorhaben...': 'Describa su proyecto...'
    },
    'fr': {
        'lang="de"': 'lang="fr"',
        'Partnerschaften & Anfragen': 'Partenariats & Demandes',
        'Reichen Sie Ihre Geschäftsidee ein, registrieren Sie sich als Investor oder stellen Sie Miet- und Kaufanfragen für unsere Projekte.': 'Soumettez votre idée d\'entreprise, inscrivez-vous comme investisseur ou envoyez vos demandes de location et d\'achat.',
        'Home': 'Accueil',
        '/de/': '/fr/',
        '>Deutschland<': '>Allemagne<',
        '>Türkei<': '>Turquie<',
        '>Anfragen<': '>Demandes<',
        '>Kontakt<': '>Contact<',
        'Wählen Sie Ihren Bereich, um schnell und unkompliziert mit uns in Kontakt zu treten.': 'Sélectionnez votre domaine pour nous contacter rapidement et facilement.',
        'Idee einreichen': 'Soumettre une idée',
        'Für Projektideen & strategische Partnerschaften (Investor gesucht)': 'Pour les idées de projets & partenariats (Investisseur recherché)',
        'Als Investor registrieren': 'Devenir investisseur',
        'Für Investoren an unseren Projekten oder Grundstücken': 'Pour les investisseurs dans nos projets ou terrains',
        'Mieten': 'Louer',
        'Immobilien oder Gewerbeflächen für Ihre Firma mieten': 'Louez des biens ou espaces commerciaux pour votre entreprise',
        'Kaufen': 'Acheter',
        'Immobilien, Grundstücke oder Beteiligungen erwerben': 'Acquérir des biens, terrains ou participations',
        'Zurück zur Auswahl': 'Retour à la sélection',
        'Vielen Dank für Ihre Anfrage!': 'Merci pour votre demande !',
        'Wir haben Ihre Daten erhalten und werden uns in Kürze bei Ihnen melden.': 'Nous avons reçu vos données et vous contacterons sous peu.',
        'Weitere Anfrage stellen': 'Soumettre une autre demande',
        'Idee einreichen (Investor gesucht)': 'Soumettre une idée (Investisseur recherché)',
        'Wenn Sie eine interessante Geschäftsidee haben und einen Investor oder strategischen Partner suchen, können Sie Ihre Idee bei uns einreichen. Wir prüfen jede Anfrage individuell. Wenn das Projekt zu uns passt, können wir selbst als Investor oder Partner einsteigen.': 'Si vous avez une idée d\'entreprise et cherchez un investisseur ou partenaire, vous pouvez la soumettre ici. Nous examinons chaque demande.',
        '>Name *<': '>Nom *<',
        'Firma (optional)': 'Société (facultatif)',
        '>E-Mail *<': '>Email *<',
        'Telefon (optional)': 'Téléphone (facultatif)',
        '>Land *<': '>Pays *<',
        '>Stadt *<': '>Ville *<',
        '>Kategorie der Idee *<': '>Catégorie de l\'idée *<',
        '>Bitte wählen<': '>Veuillez sélectionner<',
        '>Immobilienentwicklung<': '>Développement immobilier<',
        '>Technologie / Start-up<': '>Technologie / Startup<',
        '>Erneuerbare Energien<': '>Énergies renouvelables<',
        '>Handel & Gewerbe<': '>Commerce<',
        '>Sonstiges<': '>Autre<',
        'Was wird gesucht? *': 'Que recherchez-vous ? *',
        'Investor (Kapital)': 'Investisseur (Capital)',
        'Strategischer Partner': 'Partenaire stratégique',
        'Fläche / Grundstück': 'Espace / Terrain',
        'Zusammenarbeit / Joint-Venture': 'Collaboration / Joint Venture',
        'Benötigte Investitionssumme (optional)': 'Montant de l\'investissement (facultatif)',
        'Beschreibung der Idee *': 'Description de l\'idée *',
        'Datei Upload (PDF oder Präsentation) - optional': 'Téléchargement de fichier (PDF ou Présentation)',
        'Anfrage senden': 'Envoyer la demande',
        'Investoren können sich registrieren, um passende Projekte, Grundstücke oder Geschäftsmöglichkeiten mit uns zu besprechen.': 'Les investisseurs peuvent s\'inscrire pour discuter de projets ou opportunités.',
        'Bevorzugte Branche': 'Secteur préféré',
        'Bevorzugte Region': 'Région préférée',
        'Investitionsvolumen': 'Volume d\'investissement',
        'Beschreibung / Nachricht *': 'Description / Message *',
        'Was möchten Sie mieten? *': 'Que souhaitez-vous louer ? *',
        '>Grundstück<': '>Terrain<',
        '>Gewerbeobjekt<': '>Local commercial<',
        '>Ladenfläche<': '>Espace commercial<',
        '>Wohnung<': '>Appartement<',
        '>Büro<': '>Bureau<',
        'Gewünschte Größe': 'Taille souhaitée',
        '>Budget<': '>Budget<',
        '>Nutzungszweck<': '>Utilisation prévue<',
        '>Nachricht *<': '>Message *<',
        'Mietanfrage senden': 'Envoyer demande de location',
        'Was möchten Sie kaufen? *': 'Que souhaitez-vous acheter ? *',
        '>Immobilie<': '>Propriété<',
        'Beteiligung an Projekt': 'Participation au projet',
        '>Anforderungen<': '>Exigences<',
        'Kaufanfrage senden': 'Envoyer demande d\'achat',
        'Nutzungsbedingungen': 'Conditions d\'utilisation',
        'Cookie-Richtlinie': 'Politique en matière de cookies',
        'Datenschutz': 'Politique de confidentialité',
        'ihre@email.com': 'votre@email.com',
        'Ihr Name': 'Votre Nom',
        'Ihr vollständiger Name': 'Votre nom complet',
        'Firmenname': 'Nom de l\'entreprise',
        'Land der Umsetzung': 'Pays d\'implantation',
        'Wo suchen Sie?': 'Où cherchez-vous ?',
        'z.B. DACH, USA, Global': 'ex. Monde, USA',
        'Geplantes Volumen': 'Volume prévu',
        'Kurze Beschreibung Ihres Investmentfokus...': 'Brève description...',
        'Weitere Details zu Ihrer Anfrage...': 'Plus de détails...',
        'Beschreiben Sie kurz Ihr Vorhaben...': 'Décrivez votre projet...'
    },
    'tr': {
        'lang="de"': 'lang="tr"',
        'Partnerschaften & Anfragen': 'Ortaklıklar & Talepler',
        'Reichen Sie Ihre Geschäftsidee ein, registrieren Sie sich als Investor oder stellen Sie Miet- und Kaufanfragen für unsere Projekte.': 'İş fikrinizi gönderin, yatırımcı olarak kaydolun veya projelerimiz için kiralama ve satın alma talepleri gönderin.',
        'Home': 'Ana Sayfa',
        '/de/': '/tr/',
        '>Deutschland<': '>Almanya<',
        '>Türkei<': '>Türkiye<',
        '>Anfragen<': '>Talepler<',
        '>Kontakt<': '>İletişim<',
        'Wählen Sie Ihren Bereich, um schnell und unkompliziert mit uns in Kontakt zu treten.': 'Bizimle hızlıca iletişime geçmek için alanınızı seçin.',
        'Idee einreichen': 'Fikir Gönder',
        'Für Projektideen & strategische Partnerschaften (Investor gesucht)': 'Proje fikirleri ve stratejik ortaklıklar için (Yatırımcı aranıyor)',
        'Als Investor registrieren': 'Yatırımcı Olarak Kaydol',
        'Für Investoren an unseren Projekten oder Grundstücken': 'Projelerimize veya arazilerimize yatırım yapacaklar için',
        'Mieten': 'Kiralık',
        'Immobilien oder Gewerbeflächen für Ihre Firma mieten': 'Şirketiniz için emlak veya ticari alan kiralayın',
        'Kaufen': 'Satılık',
        'Immobilien, Grundstücke oder Beteiligungen erwerben': 'Emlak, arazi veya proje hisseleri satın alın',
        'Zurück zur Auswahl': 'Seçime geri dön',
        'Vielen Dank für Ihre Anfrage!': 'Talebiniz için teşekkür ederiz!',
        'Wir haben Ihre Daten erhalten und werden uns in Kürze bei Ihnen melden.': 'Verilerinizi aldık, kısa süre içinde size dönüş yapacağız.',
        'Weitere Anfrage stellen': 'Yeni talep oluştur',
        'Idee einreichen (Investor gesucht)': 'Fikir Gönder (Yatırımcı aranıyor)',
        'Wenn Sie eine interessante Geschäftsidee haben und einen Investor oder strategischen Partner suchen, können Sie Ihre Idee bei uns einreichen. Wir prüfen jede Anfrage individuell. Wenn das Projekt zu uns passt, können wir selbst als Investor oder Partner einsteigen.': 'İlginç bir iş fikriniz varsa ve yatırımcı veya ortak arıyorsanız, fikrinizi bize sunabilirsiniz. Her talebi inceliyoruz.',
        '>Name *<': '>İsim *<',
        'Firma (optional)': 'Firma (isteğe bağlı)',
        '>E-Mail *<': '>E-Posta *<',
        'Telefon (optional)': 'Telefon (isteğe bağlı)',
        '>Land *<': '>Ülke *<',
        '>Stadt *<': '>Şehir *<',
        '>Kategorie der Idee *<': '>Fikir Kategorisi *<',
        '>Bitte wählen<': '>Lütfen seçin<',
        '>Immobilienentwicklung<': '>Gayrimenkul Geliştirme<',
        '>Technologie / Start-up<': '>Teknoloji / Girişim<',
        '>Erneuerbare Energien<': '>Yenilenebilir Enerji<',
        '>Handel & Gewerbe<': '>Ticaret<',
        '>Sonstiges<': '>Diğer<',
        'Was wird gesucht? *': 'Ne aranıyor? *',
        'Investor (Kapital)': 'Yatırımcı (Sermaye)',
        'Strategischer Partner': 'Stratejik Ortak',
        'Fläche / Grundstück': 'Alan / Arazi',
        'Zusammenarbeit / Joint-Venture': 'İşbirliği',
        'Benötigte Investitionssumme (optional)': 'Gerekli Yatırım Tutarı (isteğe bağlı)',
        'Beschreibung der Idee *': 'Fikrin Açıklaması *',
        'Datei Upload (PDF oder Präsentation) - optional': 'Dosya Yükle (PDF veya Sunum)',
        'Anfrage senden': 'Talebi Gönder',
        'Investoren können sich registrieren, um passende Projekte, Grundstücke oder Geschäftsmöglichkeiten mit uns zu besprechen.': 'Yatırımcılar bizimle projeleri görüşmek için kayıt olabilir.',
        'Bevorzugte Branche': 'Tercih Edilen Sektör',
        'Bevorzugte Region': 'Tercih Edilen Bölge',
        'Investitionsvolumen': 'Yatırım Hacmi',
        'Beschreibung / Nachricht *': 'Açıklama / Mesaj *',
        'Was möchten Sie mieten? *': 'Ne kiralamak istiyorsunuz? *',
        '>Grundstück<': '>Arazi<',
        '>Gewerbeobjekt<': '>Ticari Mülk<',
        '>Ladenfläche<': '>Mağaza<',
        '>Wohnung<': '>Daire<',
        '>Büro<': '>Ofis<',
        'Gewünschte Größe': 'İstenilen Boyut',
        '>Budget<': '>Bütçe<',
        '>Nutzungszweck<': '>Kullanım Amacı<',
        '>Nachricht *<': '>Mesaj *<',
        'Mietanfrage senden': 'Kiralama Talebi Gönder',
        'Was möchten Sie kaufen? *': 'Ne satın almak istiyorsunuz? *',
        '>Immobilie<': '>Emlak<',
        'Beteiligung an Projekt': 'Projeye Katılım',
        '>Anforderungen<': '>Gereksinimler<',
        'Kaufanfrage senden': 'Satın Alma Talebi Gönder',
        'Nutzungsbedingungen': 'Kullanım Koşulları',
        'Cookie-Richtlinie': 'Çerez Politikası',
        'Datenschutz': 'Gizlilik Politikası',
        'ihre@email.com': 'sizin@emailiniz.com',
        'Ihr Name': 'Adınız',
        'Ihr vollständiger Name': 'Adınız ve Soyadınız',
        'Firmenname': 'Firma Adı',
        'Land der Umsetzung': 'Uygulama Ülkesi',
        'Wo suchen Sie?': 'Nerede Arıyorsunuz?',
        'z.B. DACH, USA, Global': 'örn. Türkiye, Global',
        'Geplantes Volumen': 'Planlanan Hacim',
        'Kurze Beschreibung Ihres Investmentfokus...': 'Yatırım odağınızın kısa açıklaması...',
        'Weitere Details zu Ihrer Anfrage...': 'Talebiniz hakkında diğer detaylar...',
        'Beschreiben Sie kurz Ihr Vorhaben...': 'Projenizi kısaca açıklayın...'
    }
}

source_file = 'de/partnerschaften.html'
with open(source_file, 'r', encoding='utf-8') as f:
    german_content = f.read()

# Fallback languages list
all_langs = ['en', 'es', 'fr', 'tr', 'zh', 'ru', 'ar', 'pt', 'he', 'hi', 'hy', 'ku', 'ur']

for lang in all_langs:
    if not os.path.exists(lang):
        os.makedirs(lang)
    
    # Use localized dictionary if available, else EN fallback, else original
    trans_dict = languages.get(lang)
    if not trans_dict and 'en' in languages:
        trans_dict = languages['en'].copy()
        trans_dict['lang="de"'] = f'lang="{lang}"'
        trans_dict['/de/'] = f'/{lang}/'

    content = german_content
    for de_str, loc_str in trans_dict.items():
        content = content.replace(de_str, loc_str)
        
    # Write translated file
    target_file = f'{lang}/partnerschaften.html'
    with open(target_file, 'w', encoding='utf-8') as f:
        f.write(content)

print(f"Generated translations for: {', '.join(all_langs)}")

